Repository 9oormthon-univ/2025_SEASONTHON_TEAM_24_BE, pull requests merged in 2025-09, with the labels that each got.

#8 소셜로그인 엔드포인트 문서화 작업 PR 입니다.
  src/main/java/com/qoormthon/empty_wallet/domain/auth/controller/OAuth2DocsController.java
Labels: documentation

#10 온보딩 화면 서베이 노출 및 풀&퀵서베이 기간 설정 작업
  settings.gradle
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/Survey.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyOption.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyType.java
Labels: feature

#12 기존 소수점 첫째자리 표시 에서 반올림되도록 수정 작업 PR 입니다.
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/Gender.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/SocialProvider.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/User.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/service/UserService.java
  src/main/java/com/qoormthon/empty_wallet/global/oauth2/OAuth2UserService.java
Labels: enhancement

#13 Develop
  settings.gradle
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/Survey.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyOption.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyType.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/Gender.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/SocialProvider.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/User.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/service/UserService.java
  src/main/java/com/qoormthon/empty_wallet/global/oauth2/OAuth2UserService.java
Labels: feature

#26 배포작업 진행합니다!(2)
  src/main/java/com/qoormthon/empty_wallet/domain/character/entity/CharCode.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/entity/Character.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/entity/Score.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/repository/CharacterRepository.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/repository/ScoreRepository.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/service/CharacterScoreService.java
  src/main/java/com/qoormthon/empty_wallet/domain/character/service/CharacterService.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/controller/StrategyController.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/docs/StrategyDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/dto/StrategyDataDTO.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/entity/StrategyActive.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/entity/StrategyStatus.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/entity/StrategyType.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/service/StrategyService.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/controller/SurveyController.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/docs/SurveyDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/dto/response/SubmitSurveyResponse.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyOption.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/entity/SurveyStatus.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/repository/SurveyOptionRepository.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/service/CharacterResolverService.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/service/SurveyCommandService.java
  src/main/java/com/qoormthon/empty_wallet/domain/survey/service/SurveyService.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/controller/UserController.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/docs/UserDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/dto/RequiredDaysRequest.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/entity/User.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/repository/UserRepository.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/service/UserService.java
  src/main/java/com/qoormthon/empty_wallet/global/common/dto/response/ListResponseDTO.java
  src/main/java/com/qoormthon/empty_wallet/global/oauth2/OAuth2LoginSuccessHandler.java
  src/main/java/com/qoormthon/empty_wallet/global/oauth2/OAuth2UserService.java
  src/main/java/com/qoormthon/empty_wallet/global/security/core/CustomUserDetailsService.java
  src/main/resources/static/data/strategyData.json
Labels: feature

#33 도전 시작하기 호출 api 작업 PR 입니다.
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/controller/StrategyController.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/docs/StrategyDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/dto/StrategyDataDTO.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/entity/StrategyActive.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/entity/StrategyStatus.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/repository/StrategyActiveRepository.java
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/service/StrategyService.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/docs/UserDocs.java
  src/main/resources/application.yml
  src/main/resources/static/data/strategyData.json
Labels: feature

#42 Feat: 목표금액, 목표 금액까지 남은 기간을 반환하는 api 구현
  src/main/java/com/qoormthon/empty_wallet/domain/strategy/docs/StrategyDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/controller/UserController.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/docs/UserDocs.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/dto/RequiredDaysAndGoalPayResponse.java
  src/main/java/com/qoormthon/empty_wallet/domain/user/service/UserService.java
Labels: feature

#45 패키지 구조 리드미에 추가하였습니다.
  README.md
Labels: documentation
